const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="vyankateshlegend@gmail.com"
global.location="Delhi,India."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Delhi";
global.github=process.env.GITHUB|| "..";
global.gurl  =process.env.GURL  || "..";
global.website=process.env.GURL || "..." ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/kKb9d29/4fadb08e1a49f8949d72b968dbe102af.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "LEGENDARY" 


global.devs = "2349156137725" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "919403621818";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349156137725";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "true"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_17_06_07_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDQsXG4gICAgICAgIDQ3LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTgyLFxuICAgICAgICAyMyxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNjgsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTk2LFxuICAgICAgICA5NCxcbiAgICAgICAgMjM1LFxuICAgICAgICAxNSxcbiAgICAgICAgNzUsXG4gICAgICAgIDE0LFxuICAgICAgICAxNjMsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxMzksXG4gICAgICAgIDcsXG4gICAgICAgIDQsXG4gICAgICAgIDM1LFxuICAgICAgICA1MSxcbiAgICAgICAgMjQxLFxuICAgICAgICA2MSxcbiAgICAgICAgNzMsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTExXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NixcbiAgICAgICAgMTk4LFxuICAgICAgICAxNzUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNzEsXG4gICAgICAgIDEzNixcbiAgICAgICAgOSxcbiAgICAgICAgMTg3LFxuICAgICAgICA5MCxcbiAgICAgICAgNDEsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTM5LFxuICAgICAgICA3NCxcbiAgICAgICAgNzcsXG4gICAgICAgIDczLFxuICAgICAgICAxNDksXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNTAsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTUwLFxuICAgICAgICAxNzYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjgsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNTMsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTczLFxuICAgICAgICAyNDMsXG4gICAgICAgIDIwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzYsXG4gICAgICAgIDQxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDQxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDM0LFxuICAgICAgICAxNTAsXG4gICAgICAgIDgxLFxuICAgICAgICA3LFxuICAgICAgICA5MixcbiAgICAgICAgMjAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNTYsXG4gICAgICAgIDUsXG4gICAgICAgIDc4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDk5LFxuICAgICAgICAyMixcbiAgICAgICAgNCxcbiAgICAgICAgNzEsXG4gICAgICAgIDM2LFxuICAgICAgICAxNixcbiAgICAgICAgMTg2LFxuICAgICAgICAyMDQsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTg2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDEyM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDIsXG4gICAgICAgIDg1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxMDQsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMzUsXG4gICAgICAgIDU1LFxuICAgICAgICAxMzksXG4gICAgICAgIDM2LFxuICAgICAgICA2NixcbiAgICAgICAgMTg4LFxuICAgICAgICAxODEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTE3LFxuICAgICAgICA5LFxuICAgICAgICAxOSxcbiAgICAgICAgMjIzLFxuICAgICAgICA1MSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNTUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTY4LFxuICAgICAgICAxNjYsXG4gICAgICAgIDYyLFxuICAgICAgICA4MixcbiAgICAgICAgOTIsXG4gICAgICAgIDg3LFxuICAgICAgICAxMTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgNzIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNTQsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTQsXG4gICAgICAgIDksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMjcsXG4gICAgICAgIDc4LFxuICAgICAgICAxODksXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjUzLFxuICAgICAgICA0NSxcbiAgICAgICAgNjIsXG4gICAgICAgIDEsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjEzLFxuICAgICAgICA2MSxcbiAgICAgICAgNDcsXG4gICAgICAgIDIwNSxcbiAgICAgICAgOSxcbiAgICAgICAgNDAsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDk4LFxuICAgICAgICAxOTUsXG4gICAgICAgIDkzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzOSxcbiAgICAgICAgNDcsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTUsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMzgsXG4gICAgICAgIDE4LFxuICAgICAgICA4LFxuICAgICAgICAxMTUsXG4gICAgICAgIDQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTk3LFxuICAgICAgICA5NCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDE4LFxuICAgICAgICAxODQsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTE5LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMzYsXG4gICAgICAgIDM0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDkzLFxuICAgICAgICAyMjAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMjUsXG4gICAgICAgIDY1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDU2LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICA2NFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgOVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQzLFxuICAgICAgICAyNTAsXG4gICAgICAgIDUxLFxuICAgICAgICAxMCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxODcsXG4gICAgICAgIDgsXG4gICAgICAgIDM1LFxuICAgICAgICAxNDMsXG4gICAgICAgIDExOCxcbiAgICAgICAgNzQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjUxLFxuICAgICAgICAxMjYsXG4gICAgICAgIDI4LFxuICAgICAgICAzMyxcbiAgICAgICAgMTU5LFxuICAgICAgICA0NSxcbiAgICAgICAgOTksXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxOTYsXG4gICAgICAgIDg0LFxuICAgICAgICA5OSxcbiAgICAgICAgNTcsXG4gICAgICAgIDIwLFxuICAgICAgICA5MixcbiAgICAgICAgMTg2LFxuICAgICAgICAxNCxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjksXG4gICAgICAgIDQyLFxuICAgICAgICAyLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTIwLFxuICAgICAgICA3LFxuICAgICAgICA1MCxcbiAgICAgICAgMTY4LFxuICAgICAgICAyNTUsXG4gICAgICAgIDEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMjAsXG4gICAgICAgIDM5LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjE0LFxuICAgICAgICAyMDUsXG4gICAgICAgIDU2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDQ3LFxuICAgICAgICAxNyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNTksXG4gICAgICAgIDEwMixcbiAgICAgICAgMjM2LFxuICAgICAgICA0OSxcbiAgICAgICAgMTAxLFxuICAgICAgICAzNSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTIzLFxuICBcImFkdlNlY3JldEtleVwiOiBcIjE2dEk3SGZISkRVditxb2JwTHN1SUJtRUg2REVoNmVta2lYMnRubjRROXc9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiNDg2OTk1NTQxMDdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjE4MDQwQTQ0N0E5NDJCQzlGNEYzNkM3NUNFQjNFN0NCXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTMyMjM1NVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjQ4Njk5NTU0MTA3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJFQjJDMzhCQzdGNTlFRTcxMDYxN0ZGODI2RUM4QkZBRlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjEzMjIzNTVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI0ODY5OTU1NDEwN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNjIyMzhCM0ZFQkE1N0JDREIyREQ1QjNDRDhGODIyQzRcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIxMzIyMzU4XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiNDg2OTk1NTQxMDdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjg5RTJBMzdENTY0NzQzRTJEOTYwNUZBMkZEMTg5QTE4XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTMyMjM1OFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJNeTdKcC1FTFNTbXZnT0FnOXdoZXRRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjlkNzMyZTE3LTVlNTEtNDFkMy05MmZkLTdjYWEyYWVhZjM4ZVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA5NCxcbiAgICAgIDE3NixcbiAgICAgIDE3NyxcbiAgICAgIDEzNyxcbiAgICAgIDE2MSxcbiAgICAgIDIyNSxcbiAgICAgIDEzNSxcbiAgICAgIDc4LFxuICAgICAgMTYwLFxuICAgICAgMTAxLFxuICAgICAgMTY0LFxuICAgICAgMjQsXG4gICAgICA5NCxcbiAgICAgIDE2NixcbiAgICAgIDEwLFxuICAgICAgMjA4LFxuICAgICAgNzUsXG4gICAgICAyMTksXG4gICAgICAxNCxcbiAgICAgIDIyOFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNzgsXG4gICAgICAxNDMsXG4gICAgICAxNTQsXG4gICAgICAxMTksXG4gICAgICA0OSxcbiAgICAgIDE3NyxcbiAgICAgIDI0MixcbiAgICAgIDIxNSxcbiAgICAgIDg1LFxuICAgICAgMTIyLFxuICAgICAgNTIsXG4gICAgICAxMzcsXG4gICAgICAzOSxcbiAgICAgIDMsXG4gICAgICA1MCxcbiAgICAgIDQyLFxuICAgICAgMjIyLFxuICAgICAgMjIxLFxuICAgICAgODcsXG4gICAgICAyMTNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiNUo5MU5CR0pcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjQ4Njk5NTU0MTA3OjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjE1MzkzMjE4MTU4MjA1ODoxQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIkxlZ2VuZGFyeVwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tDYnZNWURFTzJXNWJRR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiOXhHZldycFk2bld6K2tsbXpQOGhTd1ZYZzVTRzAyZVhkMXl1NGhJaUlXaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJRYXdFTDNwU3NONWxGd09HNHdWeXphaFByajJmMGRVZm9QNUd3UTZXNGI0M0tzenB6NEdWRGtYSHR3ek9ZUjUxTFlJWGhiVW92blBOc3dvd3RBUUlEdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJ4bDhuZ2I1M2ZnMDIwZTl1TjN1UktKeGszQUNvZ21TQjlzSXFBRHV5ZlJpSXd4QkE3SHpJdWx5VXcrZFRZS29EakVaQS8wQUVCUGVXVjhxT2pNZDJCZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI0ODY5OTU1NDEwNzoxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTA1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjEzMjIzNTMsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFQUGhcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBQaC5qc29uIjogIntcImtleURhdGFcIjpcIkxveUZkUUxUdGtGQzJPV0k2UTEzWmYwL1c2TFhyK0k3a0ZuL29GYUllWGs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTUzMDkzNTM2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjEzMjIzNTM2NDhcIn0iCn0="

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "FOR MY CRIMSON" ,
  
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "𝙻𝙴𝙶𝙴𝙽𝙳𝙰𝚁𝚈",
  botname : process.env.BOT_NAME  || "LEGENDARY",
  ownername:process.env.OWNER_NAME|| "LEGEND",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "AYANOKOJI"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
